from __future__ import annotations

from collections.abc import Iterable
from typing import TYPE_CHECKING, Protocol
from uuid import UUID

from tomatempo.domain.entities import Project, Tag, Task

if TYPE_CHECKING:
    from tomatempo.domain.entities import PomodoroSession


class ProjectRepository(Protocol):
    def save(self, project: Project) -> Project: ...

    def get_by_id(self, project_id: UUID) -> Project | None: ...

    def get_by_name(self, name: str) -> Project | None: ...

    def list(self) -> Iterable[Project]: ...


class TaskRepository(Protocol):
    def save(self, task: Task) -> Task: ...

    def get_by_id(self, task_id: UUID) -> Task | None: ...

    def get_by_project_and_title(self, project_id: UUID, title: str) -> Task | None: ...

    def list(self) -> Iterable[Task]: ...


class TagRepository(Protocol):
    def save(self, tag: Tag) -> Tag: ...

    def get_by_id(self, tag_id: UUID) -> Tag | None: ...

    def get_by_name(self, name: str) -> Tag | None: ...

    def list(self) -> Iterable[Tag]: ...


class TaskTagRepository(Protocol):
    def attach(self, task_id: UUID, tag_id: UUID) -> bool: ...

    def remove(self, task_id: UUID, tag_id: UUID) -> bool: ...

    def replace_for_task(self, task_id: UUID, tag_ids: set[UUID]) -> bool: ...

    def list_tag_ids_for_task(self, task_id: UUID) -> set[UUID]: ...


class PomodoroSessionRepository(Protocol):
    def save(self, session: PomodoroSession) -> PomodoroSession: ...

    def get_by_id(self, session_id: UUID) -> PomodoroSession | None: ...

    def get_active(self) -> PomodoroSession | None: ...

    def list(self) -> Iterable[PomodoroSession]: ...
